//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""0x0"",
            ""id"": ""82bc55d7-4b92-4b1d-8154-2a0d8f9f134d"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""9f777f07-e951-41f6-80af-22b42a30a5b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5361cb84-d4f1-4075-b9ea-68a58e038efa"",
                    ""path"": ""<MidiDevice>/note056"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // 0x0
        m__0x0 = asset.FindActionMap("0x0", throwIfNotFound: true);
        m__0x0_Newaction = m__0x0.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // 0x0
    private readonly InputActionMap m__0x0;
    private List<I_0x0Actions> m__0x0ActionsCallbackInterfaces = new List<I_0x0Actions>();
    private readonly InputAction m__0x0_Newaction;
    public struct _0x0Actions
    {
        private @NewControls m_Wrapper;
        public _0x0Actions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m__0x0_Newaction;
        public InputActionMap Get() { return m_Wrapper.m__0x0; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(_0x0Actions set) { return set.Get(); }
        public void AddCallbacks(I_0x0Actions instance)
        {
            if (instance == null || m_Wrapper.m__0x0ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m__0x0ActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(I_0x0Actions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(I_0x0Actions instance)
        {
            if (m_Wrapper.m__0x0ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(I_0x0Actions instance)
        {
            foreach (var item in m_Wrapper.m__0x0ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m__0x0ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public _0x0Actions @_0x0 => new _0x0Actions(this);
    public interface I_0x0Actions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
